name: weather_forecast
description: A simple application for weather forecasting. It should show the actual weather for your current location.

publish_to:
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Dart packages
  equatable: ^2.0.3
  get_it: ^7.2.0
  dio: ^4.0.1
  intl: ^0.17.0

  #Flutter packages
  flutter_bloc: ^8.0.0

  #Platform plugins
  shared_preferences: ^2.0.9
  location: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true
